# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

def common_pods
  pod 'Realm', '4.3.2'
  pod 'RealmSwift', '4.3.2'
  pod 'web3swift', '2.2.1'

end

post_install do |installer|
  # installer.pods_project.targets.each do |target|
  #   if ['Alamofire', 'ObjectMapper', 'FacebookLogin', 'Pulsator'].include? target.name
  #     target.build_configurations.each do |config|
  #       config.build_settings['SWIFT_VERSION'] = '4.2'
  #     end
  #   end
  # end
end

target 'AuditElections' do
  common_pods
end
